export const UNSELECT_PRODUCT = 'PRODUCT//UNSELECT'
export const FETCH_PRODUCTS = 'PRODUCTS//FETCH'
export const FETCH_PRODUCT = 'PRODUCT//FETCH'
export const FECTCH_DESCRIPTION_PRODUCT = 'PRODUCT//FETCH//DESCRIPTION'
